spec/spec_helper.rb:
  mock_with: ':rspec'
  strict_level: ':error'
  coverage_report: true
  minimum_code_coverage_percentage: 70

.gitlab-ci.yml:
  delete: true

.travis.yml:
  delete: true

appveyor.yml:
  delete: true
